version: '3.0'
services:
  app:
    # image: divante/vue-storefront-api:latest
    container_name: vsf-api
    build:
      context: .
      dockerfile: docker/vue-storefront-api/Dockerfile
    depends_on:
      - es1
      - redis
    env_file: docker/vue-storefront-api/default.env
    environment:
      VS_ENV: dev
    volumes:
      - './config:/var/www/config'
      - './ecosystem.json:/var/www/ecosystem.json'
      - './migrations:/var/www/migrations'
      - './package.json:/var/www/package.json'
      - './babel.config.js:/var/www/babel.config.js'
      - './tsconfig.json:/var/www/tsconfig.json'
      - './nodemon.json:/var/www/nodemon.json'
      - './scripts:/var/www/scripts'
      - './src:/var/www/src'
      - './var:/var/www/var'
    tmpfs:
      - /var/www/dist
#    ports:
#      - '8080:8080'
    networks:
      - web
    labels:
      traefik.enabled: "true"
      traefik.port: "8080"
      traefik.frontend.entryPoints: http,https
      traefik.frontend.headers.SSLRedirect: "true"
      traefik.api.frontend.rule: Host:vsf-api-${HOSTNAME_DELIMITER:-.}${ENVIRONMENT_FQDN:-docker.localhost}

networks:
  web:
    driver: bridge
